version: '3'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  nodejs: 
    build: 
      context: ./Server 
      dockerfile: Dockerfile 
    image: node3js 
    container_name: servidor
    ports:
      - 3000:3000
  dispositivojs: 
    build: 
      context: ./Dispositivos 
      dockerfile: Dockerfile 
    image: dispositivojs 
    container_name: dispositivos
    ports:
      - 5000:5000
