version: '3'
networks:
  default:
    external:
      name: shared-network
services:
  nodejs: 
    build: 
      context: ./Server 
      dockerfile: Dockerfile 
    image: node15js 
    container_name: servidor
    ports:
      - 3000:3000
  dispositivojs: 
    build: 
      context: ./Dispositivos 
      dockerfile: Dockerfile 
    image: dispositivo7js 
    container_name: dispositivos
    ports:
      - 5000:5000